;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from extras.el

(register-definition-prefixes "extras" '("+unfill-region" "mouse-set-region" "my/convert-org-to-docx-with-pandoc" "org-mouse-bold-mode" "sudo-edit"))


;;; Generated autoloads from mcp-server/mcp-server.el

(autoload 'mcp-server-start "mcp-server/mcp-server"
"Start the MCP server with optional DEBUG and TRANSPORT.
TRANSPORT defaults to 'unix' if not specified.
If DEBUG is non-nil, enable debug logging.

(fn &optional DEBUG TRANSPORT)" t)
(autoload 'mcp-server-start-unix "mcp-server/mcp-server"
"Start MCP server with Unix domain socket transport.
If DEBUG is non-nil, enable debug logging.
SOCKET-PATH specifies custom socket location.

(fn &optional DEBUG SOCKET-PATH)" t)
(autoload 'mcp-server-start-tcp "mcp-server/mcp-server"
"Start MCP server with TCP transport.
If DEBUG is non-nil, enable debug logging.
HOST and PORT specify the bind address (planned for future implementation).

(fn &optional DEBUG HOST PORT)" t)
(autoload 'mcp-server-toggle-debug "mcp-server/mcp-server"
"Toggle debug logging for the MCP server." t)
(autoload 'mcp-server-status "mcp-server/mcp-server"
"Show the status of the MCP server." t)
(autoload 'mcp-server-list-clients "mcp-server/mcp-server"
"List all connected MCP clients." t)
(autoload 'mcp-server-get-socket-path "mcp-server/mcp-server"
"Get the current Unix socket path if using Unix transport." t)
(autoload 'mcp-server-disconnect-client "mcp-server/mcp-server"
"Disconnect a specific CLIENT-ID.

(fn CLIENT-ID)" t)
(autoload 'mcp-server-start-unix-named "mcp-server/mcp-server"
"Start MCP server with Unix socket using SOCKET-NAME.
SOCKET-NAME can be a string for fixed naming, or 'user/'session for strategies.
If DEBUG is non-nil, enable debug logging.

(fn SOCKET-NAME &optional DEBUG)" t)
(autoload 'mcp-server-set-socket-name "mcp-server/mcp-server"
"Set the socket name configuration for future server starts.
SOCKET-NAME can be:
- String: Fixed socket name (e.g., \"primary\")
- 'user: Username-based naming
- 'session: Session-based naming
- Function: Custom naming function
- nil: Revert to PID-based naming

(fn SOCKET-NAME)" t)
(autoload 'mcp-server-show-socket-config "mcp-server/mcp-server"
"Show current socket naming configuration." t)
(autoload 'mcp-server-get-predicted-socket-path "mcp-server/mcp-server"
"Get the socket path that would be used if server started now." t)
(register-definition-prefixes "mcp-server/mcp-server" '("mcp-server-"))


;;; Generated autoloads from mcp-server/mcp-server-emacs-tools.el

(register-definition-prefixes "mcp-server/mcp-server-emacs-tools" '("mcp-server-emacs-tools-"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-diagnostics.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-diagnostics" '("mcp-server-emacs-tools--"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-eval-elisp.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-eval-elisp" '("mcp-server-emacs-tools--eval-elisp-handler"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-agenda.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-agenda" '("mcp-server-emacs-tools-org-agenda--"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-archive.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-archive" '("mcp-server-emacs-tools-org-archive--handler"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-capture.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-capture" '("mcp-server-emacs-tools-org-capture--"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-clock.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-clock" '("mcp-server-emacs-tools-org-clock--handler"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-common.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-common" '("mcp-server-emacs-tools-org-"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-get-node.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-get-node" '("mcp-server-emacs-tools-org-get-node--"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-list-tags.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-list-tags" '("mcp-server-emacs-tools-org-list-tags--"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-list-templates.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-list-templates" '("mcp-server-emacs-tools-org-list-templates--"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-refile.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-refile" '("mcp-server-emacs-tools-org-refile--handler"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-roam-capture.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-roam-capture" '("mcp-server-emacs-tools-org-roam-capture--"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-roam-get-node.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-roam-get-node" '("mcp-server-emacs-tools-org-roam-get-node--handler"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-roam-search.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-roam-search" '("mcp-server-emacs-tools-org-roam-search--"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-search.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-search" '("mcp-server-emacs-tools-org-search--"))


;;; Generated autoloads from mcp-server/tools/mcp-server-emacs-tools-org-update-node.el

(register-definition-prefixes "mcp-server/tools/mcp-server-emacs-tools-org-update-node" '("mcp-server-emacs-tools-org-update-node--"))


;;; Generated autoloads from mcp-server/mcp-server-security.el

(register-definition-prefixes "mcp-server/mcp-server-security" '("mcp-server-security-"))


;;; Generated autoloads from mcp-server/mcp-server-tools.el

(register-definition-prefixes "mcp-server/mcp-server-tools" '("mcp-server-"))


;;; Generated autoloads from mcp-server/mcp-server-transport.el

(register-definition-prefixes "mcp-server/mcp-server-transport" '("mcp-server-transport-"))


;;; Generated autoloads from mcp-server/mcp-server-transport-tcp.el

(register-definition-prefixes "mcp-server/mcp-server-transport-tcp" '("mcp-server-transport-tcp-"))


;;; Generated autoloads from mcp-server/mcp-server-transport-unix.el

(register-definition-prefixes "mcp-server/mcp-server-transport-unix" '("mcp-server-transport-unix-"))


;;; Generated autoloads from ob-jshell.el

(register-definition-prefixes "ob-jshell" '("ob-jshell-command" "org-babel-"))


;;; Generated autoloads from ob-scala.el

(register-definition-prefixes "ob-scala" '("org-babel-"))


;;; Generated autoloads from ob-scala-cli.el

(register-definition-prefixes "ob-scala-cli" '("ob-scala-cli-" "org-babel-"))


;;; Generated autoloads from org-find-file-tags.el

(register-definition-prefixes "org-find-file-tags" '("org-"))


;;; Generated autoloads from mcp-server/test/config/test-config.el

(register-definition-prefixes "mcp-server/test/config/test-config" '("mcp-test-"))


;;; Generated autoloads from mcp-server/test/fixtures/test-helpers.el

(register-definition-prefixes "mcp-server/test/fixtures/test-helpers" '("mcp-test-"))


;;; Generated autoloads from mcp-server/test/unit/test-mcp-org-roam-capture.el

(register-definition-prefixes "mcp-server/test/unit/test-mcp-org-roam-capture" '("mcp-test-roam-available"))


;;; Generated autoloads from mcp-server/test/unit/test-mcp-org-roam-get-node.el

(register-definition-prefixes "mcp-server/test/unit/test-mcp-org-roam-get-node" '("mcp-test-roam-available"))


;;; Generated autoloads from mcp-server/test/unit/test-mcp-org-roam-search.el

(register-definition-prefixes "mcp-server/test/unit/test-mcp-org-roam-search" '("mcp-test-roam-available"))

;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
