#!/bin/bash 

userresources=$HOME/.config/sx/.Xresources

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

setxkbmap -option 'ctrl:nocaps'
xset -b # no beep 
xset r rate 300 50

exec dbus-run-session -- ~/.config/sx/start-session.sh
