#!/bin/bash 

userresources=$HOME/.config/sx/.Xresources

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

setxkbmap -option 'ctrl:nocaps'

xset -b # no beep 
/usr/libexec/xfce-polkit &
xset r rate 300 50
picom --config ~/.config/picom/picom.conf &
#feh --no-fehbg --bg-scale ~/Documents/Pictures/wallpapers/wall.jpg &
wmname LG3D &
/usr/bin/xsettingsd &
dbus-run-session pipewire &
dbus-run-session fvwm3 -v
#case $XDG_VTNR in
    #1) exec startxfce4 ;;
    #2) exec fvwm3 ;;
    #3) exec startkde ;;
    #4) exec fvwm3 ;;
#esac
