table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;
        
        iifname "lo" accept
        
        ct state established,related accept
        
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept
        
        udp sport 67 udp dport 68 accept

        udp dport 53 ip saddr { 10.0.0.0/24, 10.0.1.0/24 } accept
        tcp dport 53 ip saddr { 10.0.0.0/24, 10.0.1.0/24 } accept
        
        ip saddr { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } accept
        
        # tcp dport ssh accept comment "Accept SSH on port 22"

        # tcp dport { 80, 443, 8080, 3000, 5000, 8000 } accept comment "Dev servers"
        
        limit rate 5/minute log prefix "INPUT DROP: "
    }
    
    chain output {
            type filter hook output priority filter; policy accept;
    }
    
    chain forward {
            type filter hook forward priority filter; policy drop;
    
            ct state established,related accept

            # Docker
            iifname "docker0" accept
            oifname "docker0" accept
            iifname "br-*" accept  
            oifname "br-*" accept

            # Podman
            iifname "cni0" accept
            oifname "cni0" accept
            iifname "podman*" accept
            oifname "podman*" accept
            iifname "cni-podman*" accept
            oifname "cni-podman*" accept

            # k3d, k3s
            iifname "flannel*" accept
            oifname "flannel*" accept
            iifname "cali*" accept
            oifname "cali*" accept

            # VirtualBox
            iifname "vboxnet*" accept
            oifname "vboxnet*" accept

            iifname { "docker0", "br-*", "cni0", "podman*", "cni-podman*" } oifname "enp3s0" accept
            iifname "enp3s0" oifname { "docker0", "br-*", "cni0", "podman*", "cni-podman*" } ct state established,related accept

            # Wi-Fi 
            # iifname { "docker0", "br-*", "cni0", "podman*" } oifname "wlan0" accept
            # iifname "wlan0" oifname { "docker0", "br-*", "cni0", "podman*" } ct state established,related accept

            limit rate 5/minute log prefix "FORWARD DROP: "

    }
}
