# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bash = {
    pname = "bash";
    version = "a06c2e4415e9bc0346c6b86d401879ffb44058f7";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-bash";
      rev = "a06c2e4415e9bc0346c6b86d401879ffb44058f7";
      fetchSubmodules = false;
      sha256 = "sha256-ONQ1Ljk3aRWjElSWD2crCFZraZoRj3b3/VELz1789GE=";
    };
    date = "2025-12-02";
  };
  c = {
    pname = "c";
    version = "ae19b676b13bdcc13b7665397e6d9b14975473dd";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-c";
      rev = "ae19b676b13bdcc13b7665397e6d9b14975473dd";
      fetchSubmodules = false;
      sha256 = "sha256-i40dlg12UNR3dUWtdlYLZKsusYUWzu+QgC2iedRk968=";
    };
    date = "2025-09-14";
  };
  c-sharp = {
    pname = "c-sharp";
    version = "88366631d598ce6595ec655ce1591b315cffb14c";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-c-sharp";
      rev = "88366631d598ce6595ec655ce1591b315cffb14c";
      fetchSubmodules = false;
      sha256 = "sha256-x2JQKMCyvqJkVuQPfAmoihSaBxgWaTFadkmZOuc58Bc=";
    };
    date = "2026-02-17";
  };
  c3 = {
    pname = "c3";
    version = "302fab443c2237e3b8fb3e991454db0e442af130";
    src = fetchFromGitHub {
      owner = "c3lang";
      repo = "tree-sitter-c3";
      rev = "302fab443c2237e3b8fb3e991454db0e442af130";
      fetchSubmodules = false;
      sha256 = "sha256-HAHjYLvI9Hrhl+u21WYn+elSoXGH4BVuKhRKOX0f0us=";
    };
    date = "2026-01-29";
  };
  clojure = {
    pname = "clojure";
    version = "e43eff80d17cf34852dcd92ca5e6986d23a7040f";
    src = fetchFromGitHub {
      owner = "sogaiu";
      repo = "tree-sitter-clojure";
      rev = "e43eff80d17cf34852dcd92ca5e6986d23a7040f";
      fetchSubmodules = false;
      sha256 = "sha256-jokekIuuQLx5UtuPs4XAI+euispeFCwSQByVKVelrC4=";
    };
    date = "2025-08-26";
  };
  cmake = {
    pname = "cmake";
    version = "c7b2a71e7f8ecb167fad4c97227c838439280175";
    src = fetchFromGitHub {
      owner = "uyha";
      repo = "tree-sitter-cmake";
      rev = "c7b2a71e7f8ecb167fad4c97227c838439280175";
      fetchSubmodules = false;
      sha256 = "sha256-+Lom3xjPmhhZr3G4aV054lbhLjvJsPaQalSqkKUijvU=";
    };
    date = "2025-10-17";
  };
  cpp = {
    pname = "cpp";
    version = "12bd6f7e96080d2e70ec51d4068f2f66120dde35";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-cpp";
      rev = "12bd6f7e96080d2e70ec51d4068f2f66120dde35";
      fetchSubmodules = false;
      sha256 = "sha256-vmXTv6Idf0Le5ZVa8Rc1DVefqzUxkGeLGsYcSDNBpQU=";
    };
    date = "2025-09-27";
  };
  css = {
    pname = "css";
    version = "dda5cfc5722c429eaba1c910ca32c2c0c5bb1a3f";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-css";
      rev = "dda5cfc5722c429eaba1c910ca32c2c0c5bb1a3f";
      fetchSubmodules = false;
      sha256 = "sha256-jFsnEyS+FThk7L48FzAdSp5fNPSLvM8hTL/VC5FMlOE=";
    };
    date = "2025-09-28";
  };
  dart = {
    pname = "dart";
    version = "23e3921190eb9746cec64167f6110c987c7f95c6";
    src = fetchFromGitHub {
      owner = "ast-grep";
      repo = "tree-sitter-dart";
      rev = "23e3921190eb9746cec64167f6110c987c7f95c6";
      fetchSubmodules = false;
      sha256 = "sha256-836ABMYw4EnsT/DoS1AZ3URBLGYUbcjHARL0X6/8RnI=";
    };
    date = "2023-01-24";
  };
  dockerfile = {
    pname = "dockerfile";
    version = "971acdd908568b4531b0ba28a445bf0bb720aba5";
    src = fetchFromGitHub {
      owner = "camdencheek";
      repo = "tree-sitter-dockerfile";
      rev = "971acdd908568b4531b0ba28a445bf0bb720aba5";
      fetchSubmodules = false;
      sha256 = "sha256-WJJ/rjFea1sudGIyjKGupwm39TJ1zbyWlLgoRf1KCBI=";
    };
    date = "2025-01-12";
  };
  doxygen = {
    pname = "doxygen";
    version = "ccd998f378c3f9345ea4eeb223f56d7b84d16687";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-doxygen";
      rev = "ccd998f378c3f9345ea4eeb223f56d7b84d16687";
      fetchSubmodules = false;
      sha256 = "sha256-Yh6FaRvWmeqnSnBgOojWbs1wJaeEoNJlvSEqgzjGh7o=";
    };
    date = "2024-06-09";
  };
  elisp = {
    pname = "elisp";
    version = "29b4e49275f4a947ce17c8533bc20a1f97768c70";
    src = fetchFromGitHub {
      owner = "Wilfred";
      repo = "tree-sitter-elisp";
      rev = "29b4e49275f4a947ce17c8533bc20a1f97768c70";
      fetchSubmodules = false;
      sha256 = "sha256-vemNtoFr4HDGPtk7ATfBgKQrd1hZ7ndKFMUKc67rXIE=";
    };
    date = "2025-11-16";
  };
  elixir = {
    pname = "elixir";
    version = "d24cecee673c4c770f797bac6f87ae4b6d7ddec5";
    src = fetchFromGitHub {
      owner = "elixir-lang";
      repo = "tree-sitter-elixir";
      rev = "d24cecee673c4c770f797bac6f87ae4b6d7ddec5";
      fetchSubmodules = false;
      sha256 = "sha256-nSXXMPneL/sTdkpcsxUz73DiXVuNxVHnf8b2LTbAUs8=";
    };
    date = "2025-08-21";
  };
  erlang = {
    pname = "erlang";
    version = "f21023bbd6cd30cadbc793d80ae4d990d9be86fc";
    src = fetchFromGitHub {
      owner = "WhatsApp";
      repo = "tree-sitter-erlang";
      rev = "f21023bbd6cd30cadbc793d80ae4d990d9be86fc";
      fetchSubmodules = false;
      sha256 = "sha256-tDWLmveL+7s9vFVKtmSzGbx4A3X6rkaW1MR/9VOKLCg=";
    };
    date = "2025-12-22";
  };
  glsl = {
    pname = "glsl";
    version = "24a6c8ef698e4480fecf8340d771fbcb5de8fbb4";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-glsl";
      rev = "24a6c8ef698e4480fecf8340d771fbcb5de8fbb4";
      fetchSubmodules = false;
      sha256 = "sha256-TjF79WH3bX4nueYr8CbPptkNb2lNkHQNB0VZoMB35Nk=";
    };
    date = "2025-03-16";
  };
  go = {
    pname = "go";
    version = "2346a3ab1bb3857b48b29d779a1ef9799a248cd7";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-go";
      rev = "2346a3ab1bb3857b48b29d779a1ef9799a248cd7";
      fetchSubmodules = false;
      sha256 = "sha256-fifTM/m2Mxd7kpJBlzwWGheAKGq6QbbzyxpBSyplYa0=";
    };
    date = "2025-09-15";
  };
  gomod = {
    pname = "gomod";
    version = "2e886870578eeba1927a2dc4bd2e2b3f598c5f9a";
    src = fetchFromGitHub {
      owner = "camdencheek";
      repo = "tree-sitter-go-mod";
      rev = "2e886870578eeba1927a2dc4bd2e2b3f598c5f9a";
      fetchSubmodules = false;
      sha256 = "sha256-OfhV3lxdyIhA3XZYbafEtdOsQsTCSSCBrN3WbzSVg0g=";
    };
    date = "2025-10-22";
  };
  gpr = {
    pname = "gpr";
    version = "cea857d3c18d1385d1f5b66cd09ea1e44173945c";
    src = fetchFromGitHub {
      owner = "brownts";
      repo = "tree-sitter-gpr";
      rev = "cea857d3c18d1385d1f5b66cd09ea1e44173945c";
      fetchSubmodules = false;
      sha256 = "sha256-tqff8Aaj9uebJeNYuNdaDBllsj/mwRStWhhY3zB8xlU=";
    };
    date = "2024-08-12";
  };
  haskell = {
    pname = "haskell";
    version = "0975ef72fc3c47b530309ca93937d7d143523628";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-haskell";
      rev = "0975ef72fc3c47b530309ca93937d7d143523628";
      fetchSubmodules = false;
      sha256 = "sha256-0wmdbXHZbHkv4pTrB1fCbExx9E83l+zaocGa+SvQsZQ=";
    };
    date = "2025-01-31";
  };
  heex = {
    pname = "heex";
    version = "b5a7cb5f74dc695a9ff5f04919f872ebc7a895e9";
    src = fetchFromGitHub {
      owner = "phoenixframework";
      repo = "tree-sitter-heex";
      rev = "b5a7cb5f74dc695a9ff5f04919f872ebc7a895e9";
      fetchSubmodules = false;
      sha256 = "sha256-hSe3h05IFEKMosB2r/85JnT2kv/krU2Ebaszd+m3j8g=";
    };
    date = "2025-11-11";
  };
  html = {
    pname = "html";
    version = "73a3947324f6efddf9e17c0ea58d454843590cc0";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-html";
      rev = "73a3947324f6efddf9e17c0ea58d454843590cc0";
      fetchSubmodules = false;
      sha256 = "sha256-WT8ZHU4wDNovIAWbHNSvjx6zmaTn8XH3IobsckIVXxg=";
    };
    date = "2025-09-15";
  };
  janet-simple = {
    pname = "janet-simple";
    version = "d183186995204314700be3e9e0a48053ea16b350";
    src = fetchFromGitHub {
      owner = "sogaiu";
      repo = "tree-sitter-janet-simple";
      rev = "d183186995204314700be3e9e0a48053ea16b350";
      fetchSubmodules = false;
      sha256 = "sha256-zETOH+HpHyiCdOiggRy7VVjOv/WVRDb4qQ+kN9r2Frc=";
    };
    date = "2026-02-10";
  };
  java = {
    pname = "java";
    version = "e10607b45ff745f5f876bfa3e94fbcc6b44bdc11";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-java";
      rev = "e10607b45ff745f5f876bfa3e94fbcc6b44bdc11";
      fetchSubmodules = false;
      sha256 = "sha256-XoaHRQ0esrV9e5JFSZkVR7QkGfky9NMnXaLQl8lohAM=";
    };
    date = "2025-09-14";
  };
  javascript = {
    pname = "javascript";
    version = "58404d8cf191d69f2674a8fd507bd5776f46cb11";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-javascript";
      rev = "58404d8cf191d69f2674a8fd507bd5776f46cb11";
      fetchSubmodules = false;
      sha256 = "sha256-+fbTNX7qz6Ew1NrXF49wQh3RVl2ZQ3R7YXMkclUoNT8=";
    };
    date = "2025-09-14";
  };
  jsdoc = {
    pname = "jsdoc";
    version = "658d18dcdddb75c760363faa4963427a7c6b52db";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-jsdoc";
      rev = "658d18dcdddb75c760363faa4963427a7c6b52db";
      fetchSubmodules = false;
      sha256 = "sha256-xjLC56NiOwwb5BJ2DLiG3rknMR3rrcYrPuHI24NVL+M=";
    };
    date = "2025-09-13";
  };
  json = {
    pname = "json";
    version = "001c28d7a29832b06b0e831ec77845553c89b56d";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-json";
      rev = "001c28d7a29832b06b0e831ec77845553c89b56d";
      fetchSubmodules = false;
      sha256 = "sha256-cUjbN+e8UtoLRm8ZnxG7iRGD5YIc032RbHBIlmV8aLc=";
    };
    date = "2025-09-14";
  };
  julia = {
    pname = "julia";
    version = "e0f9dcd180fdcfcfa8d79a3531e11d99e79321d3";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-julia";
      rev = "e0f9dcd180fdcfcfa8d79a3531e11d99e79321d3";
      fetchSubmodules = false;
      sha256 = "sha256-Jk2jby7vWWSdnUU8s8zIIfyXFt7keWPJPyTyxPBrqBw=";
    };
    date = "2025-11-08";
  };
  kotlin = {
    pname = "kotlin";
    version = "87f81d4bd596c8fbdc28c2fc56a3daa0c0690fee";
    src = fetchFromGitHub {
      owner = "fwcd";
      repo = "tree-sitter-kotlin";
      rev = "87f81d4bd596c8fbdc28c2fc56a3daa0c0690fee";
      fetchSubmodules = false;
      sha256 = "sha256-SgU0b7Pdo/9vkD8Wi07rYpBGqKdm7jUFPTL9vt+E5dY=";
    };
    date = "2026-02-20";
  };
  lua = {
    pname = "lua";
    version = "e40f5b6e6df9c2d1d6d664ff5d346a75d71ee6b2";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-lua";
      rev = "e40f5b6e6df9c2d1d6d664ff5d346a75d71ee6b2";
      fetchSubmodules = false;
      sha256 = "sha256-tBD2Z+t0YafUeeV7xsFS9Cwe6dR9WewYh2yL/GcIfFw=";
    };
    date = "2026-01-21";
  };
  magik = {
    pname = "magik";
    version = "2965aa0c91dd096ed28c1617e85d6220a32aa1d8";
    src = fetchFromGitHub {
      owner = "krn-robin";
      repo = "tree-sitter-magik";
      rev = "2965aa0c91dd096ed28c1617e85d6220a32aa1d8";
      fetchSubmodules = false;
      sha256 = "sha256-o/4c4x2KjFtFOZz2ImOczvqxLz2CfjwlX02lHlJnNfo=";
    };
    date = "2026-02-10";
  };
  make = {
    pname = "make";
    version = "5e9e8f8ff3387b0edcaa90f46ddf3629f4cfeb1d";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-make";
      rev = "5e9e8f8ff3387b0edcaa90f46ddf3629f4cfeb1d";
      fetchSubmodules = false;
      sha256 = "sha256-WiuhAp9JZKLd0wKCui9MV7AYFOW9dCbUp+kkVl1OEz0=";
    };
    date = "2024-12-21";
  };
  markdown = {
    pname = "markdown";
    version = "cee71b8288f2ec09c29415219ac15a654bd571b9";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-markdown";
      rev = "cee71b8288f2ec09c29415219ac15a654bd571b9";
      fetchSubmodules = false;
      sha256 = "sha256-8ZNPVaJoiTh1RSVwMsH8d6zG/asbNvDA2DOqHhKd3k0=";
    };
    date = "2026-02-17";
  };
  markdown-inline = {
    pname = "markdown-inline";
    version = "cee71b8288f2ec09c29415219ac15a654bd571b9";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-markdown";
      rev = "cee71b8288f2ec09c29415219ac15a654bd571b9";
      fetchSubmodules = false;
      sha256 = "sha256-8ZNPVaJoiTh1RSVwMsH8d6zG/asbNvDA2DOqHhKd3k0=";
    };
    date = "2026-02-17";
  };
  nix = {
    pname = "nix";
    version = "eabf96807ea4ab6d6c7f09b671a88cd483542840";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "tree-sitter-nix";
      rev = "eabf96807ea4ab6d6c7f09b671a88cd483542840";
      fetchSubmodules = false;
      sha256 = "sha256-cSiBd0XkSR8l1CF2vkThWUtMxqATwuxCNO5oy2kyOZY=";
    };
    date = "2025-12-03";
  };
  org = {
    pname = "org";
    version = "64cfbc213f5a83da17632c95382a5a0a2f3357c1";
    src = fetchFromGitHub {
      owner = "milisims";
      repo = "tree-sitter-org";
      rev = "64cfbc213f5a83da17632c95382a5a0a2f3357c1";
      fetchSubmodules = false;
      sha256 = "sha256-/03eZBbv23W5s/GbDgPgaJV5TyK+/lrWUVeINRS5wtA=";
    };
    date = "2023-06-19";
  };
  perl = {
    pname = "perl";
    version = "973ea86be2a8d2db37a8a09155302ff4983fe876";
    src = fetchFromGitHub {
      owner = "ganezdragon";
      repo = "tree-sitter-perl";
      rev = "973ea86be2a8d2db37a8a09155302ff4983fe876";
      fetchSubmodules = false;
      sha256 = "sha256-z4TB9F9D5Iw1pZLOuZZgIH5U/dDudbdrBXUBlm+nIPc=";
    };
    date = "2026-01-25";
  };
  php = {
    pname = "php";
    version = "015ce839db5ae9ceda763bf12e071867fbe8cc89";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-php";
      rev = "015ce839db5ae9ceda763bf12e071867fbe8cc89";
      fetchSubmodules = false;
      sha256 = "sha256-fi4J7/AdV0wcpCg4gqmaE2epN51G4x4V5OHh7WtzGac=";
    };
    date = "2026-02-01";
  };
  proto = {
    pname = "proto";
    version = "42d82fa18f8afe59b5fc0b16c207ee4f84cb185f";
    src = fetchFromGitHub {
      owner = "mitchellh";
      repo = "tree-sitter-proto";
      rev = "42d82fa18f8afe59b5fc0b16c207ee4f84cb185f";
      fetchSubmodules = false;
      sha256 = "sha256-cX+0YARIa9i8UymPPviyoj+Wh37AFYl9fsoNZMQXPgA=";
    };
    date = "2021-06-12";
  };
  python = {
    pname = "python";
    version = "26855eabccb19c6abf499fbc5b8dc7cc9ab8bc64";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-python";
      rev = "26855eabccb19c6abf499fbc5b8dc7cc9ab8bc64";
      fetchSubmodules = false;
      sha256 = "sha256-gHeja/X/Ux8fa5rh0b69/bcUcmHBcXsK5uJ1ibtuI20=";
    };
    date = "2025-09-15";
  };
  ruby = {
    pname = "ruby";
    version = "ab6dca77a8184abc94af6e3e82538741b5078d63";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-ruby";
      rev = "ab6dca77a8184abc94af6e3e82538741b5078d63";
      fetchSubmodules = false;
      sha256 = "sha256-qAO2qRvaYlyCdSuiYBoQG/jAWiZEA5p67BTPdoK0dnU=";
    };
    date = "2026-01-24";
  };
  rust = {
    pname = "rust";
    version = "261b20226c04ef601adbdf185a800512a5f66291";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-rust";
      rev = "261b20226c04ef601adbdf185a800512a5f66291";
      fetchSubmodules = false;
      sha256 = "sha256-i6OrbcHNkrsAW5cpYOI7r0F6xn94KZWB9ZJMUH+k2ds=";
    };
    date = "2025-10-06";
  };
  scala = {
    pname = "scala";
    version = "97aead18d97708190a51d4f551ea9b05b60641c9";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-scala";
      rev = "97aead18d97708190a51d4f551ea9b05b60641c9";
      fetchSubmodules = false;
      sha256 = "sha256-INJKij5XzeIkmdemTbrkucdUo9PJOrHKf4rcf6s9OSw=";
    };
    date = "2025-08-07";
  };
  scss = {
    pname = "scss";
    version = "bca847c1410f7dd97e13fbe7838b3c2c203fb473";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-scss";
      rev = "bca847c1410f7dd97e13fbe7838b3c2c203fb473";
      fetchSubmodules = false;
      sha256 = "sha256-ynj/kBVK5llP1sNeqJQtFb6axMi3OHf9DZY6cfnLu2w=";
    };
    date = "2025-09-09";
  };
  sdml = {
    pname = "sdml";
    version = "1b9cebf8fd5a83c36456111c8c0a7a664ce78fb3";
    src = fetchFromGitHub {
      owner = "sdm-lang";
      repo = "tree-sitter-sdml";
      rev = "1b9cebf8fd5a83c36456111c8c0a7a664ce78fb3";
      fetchSubmodules = false;
      sha256 = "sha256-5H12cxmSXInDDtdSpd+rtIWauB9VDDVQ6uorrLr3wvc=";
    };
    date = "2025-10-30";
  };
  souffle = {
    pname = "souffle";
    version = "31c6bd7bb6dfe659d7c010e829d7e9ad621a8a6c";
    src = fetchFromGitHub {
      owner = "chaosite";
      repo = "tree-sitter-souffle";
      rev = "31c6bd7bb6dfe659d7c010e829d7e9ad621a8a6c";
      fetchSubmodules = false;
      sha256 = "sha256-3Remv8jy6/Gf34nimOqStuFzQLgwrx3ddrFFg7xLe+I=";
    };
    date = "2023-05-09";
  };
  sql = {
    pname = "sql";
    version = "c1f682d45742789889fdf9f73d47d07b79df8fb5";
    src = fetchFromGitHub {
      owner = "DerekStride";
      repo = "tree-sitter-sql";
      rev = "c1f682d45742789889fdf9f73d47d07b79df8fb5";
      fetchSubmodules = false;
      sha256 = "sha256-12pFFkBmyiicB56vbSM2JGX8tcUZ7mFiNfh1k1A0l54=";
    };
    date = "2026-02-17";
  };
  surface = {
    pname = "surface";
    version = "f4586b35ac8548667a9aaa4eae44456c1f43d032";
    src = fetchFromGitHub {
      owner = "connorlay";
      repo = "tree-sitter-surface";
      rev = "f4586b35ac8548667a9aaa4eae44456c1f43d032";
      fetchSubmodules = false;
      sha256 = "sha256-Fn/pF8yvU+Ll7WmoMHnEcNxb3dsfNhuKhXA1UgXeviA=";
    };
    date = "2022-01-18";
  };
  toml = {
    pname = "toml";
    version = "64b56832c2cffe41758f28e05c756a3a98d16f41";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-toml";
      rev = "64b56832c2cffe41758f28e05c756a3a98d16f41";
      fetchSubmodules = false;
      sha256 = "sha256-m9RlGkHiOL/PNENrdEPqtPlahSqGymsx7gZrCoN/Lsk=";
    };
    date = "2024-12-02";
  };
  tsx = {
    pname = "tsx";
    version = "75b3874edb2dc714fb1fd77a32013d0f8699989f";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-typescript";
      rev = "75b3874edb2dc714fb1fd77a32013d0f8699989f";
      fetchSubmodules = false;
      sha256 = "sha256-A0M6IBoY87ekSV4DfGHDU5zzFWdLjGqSyVr6VENgA+s=";
    };
    date = "2025-01-30";
  };
  typescript = {
    pname = "typescript";
    version = "75b3874edb2dc714fb1fd77a32013d0f8699989f";
    src = fetchFromGitHub {
      owner = "tree-sitter";
      repo = "tree-sitter-typescript";
      rev = "75b3874edb2dc714fb1fd77a32013d0f8699989f";
      fetchSubmodules = false;
      sha256 = "sha256-A0M6IBoY87ekSV4DfGHDU5zzFWdLjGqSyVr6VENgA+s=";
    };
    date = "2025-01-30";
  };
  typst = {
    pname = "typst";
    version = "46cf4ded12ee974a70bf8457263b67ad7ee0379d";
    src = fetchFromGitHub {
      owner = "uben0";
      repo = "tree-sitter-typst";
      rev = "46cf4ded12ee974a70bf8457263b67ad7ee0379d";
      fetchSubmodules = false;
      sha256 = "sha256-s/9R3DKA6dix6BkU4mGXaVggE4bnzOyu20T1wuqHQxk=";
    };
    date = "2025-02-10";
  };
  vala = {
    pname = "vala";
    version = "97e6db3c8c73b15a9541a458d8e797a07f588ef4";
    src = fetchFromGitHub {
      owner = "vala-lang";
      repo = "tree-sitter-vala";
      rev = "97e6db3c8c73b15a9541a458d8e797a07f588ef4";
      fetchSubmodules = false;
      sha256 = "sha256-hAekweZGDHVrWVd04RrN+9Jz0D2kode+DpceTlUXii0=";
    };
    date = "2024-10-29";
  };
  verilog = {
    pname = "verilog";
    version = "7c4b01b7df2f6e7fa1f698c9d30ac8f93af18ed2";
    src = fetchFromGitHub {
      owner = "gmlarumbe";
      repo = "tree-sitter-systemverilog";
      rev = "7c4b01b7df2f6e7fa1f698c9d30ac8f93af18ed2";
      fetchSubmodules = false;
      sha256 = "sha256-u0a8yQfFwYbAhuT8VZjKPuTfBNwAaQ0e25CcIek0thc=";
    };
    date = "2025-10-14";
  };
  vhdl = {
    pname = "vhdl";
    version = "a3b2d84990527c7f8f4ae219c332c00c33d2d8e5";
    src = fetchFromGitHub {
      owner = "alemuller";
      repo = "tree-sitter-vhdl";
      rev = "a3b2d84990527c7f8f4ae219c332c00c33d2d8e5";
      fetchSubmodules = false;
      sha256 = "sha256-CtlhSAKp90nXLI5g+vAd0dZZxjPTyMcNFvHL8DBY4j8=";
    };
    date = "2022-01-08";
  };
  wgsl = {
    pname = "wgsl";
    version = "27ae4db1458d5ea7555300c9e93c6273723d420c";
    src = fetchFromGitHub {
      owner = "mehmetoguzderin";
      repo = "tree-sitter-wgsl";
      rev = "27ae4db1458d5ea7555300c9e93c6273723d420c";
      fetchSubmodules = false;
      sha256 = "sha256-zlkU4OB259NUEc1diP5sbSKlsiYWfY333UbtoUklBvI=";
    };
    date = "2022-06-14";
  };
  yaml = {
    pname = "yaml";
    version = "4463985dfccc640f3d6991e3396a2047610cf5f8";
    src = fetchFromGitHub {
      owner = "tree-sitter-grammars";
      repo = "tree-sitter-yaml";
      rev = "4463985dfccc640f3d6991e3396a2047610cf5f8";
      fetchSubmodules = false;
      sha256 = "sha256-nCyGepZg6n2a/Clc0NFxTSt3Pm1z4OHIzJSjrjGudmw=";
    };
    date = "2026-01-25";
  };
  zig = {
    pname = "zig";
    version = "a80a6e9be81b33b182ce6305ae4ea28e29211bd5";
    src = fetchFromGitHub {
      owner = "maxxnino";
      repo = "tree-sitter-zig";
      rev = "a80a6e9be81b33b182ce6305ae4ea28e29211bd5";
      fetchSubmodules = false;
      sha256 = "sha256-o3RAbW8kLSfKxuQ/z7WDb5BaDVxZUG5oFutovRkErjk=";
    };
    date = "2024-10-13";
  };
}
