vo=gpu-next
# gpu-api=opengl # держит карточку в P0
gpu-api=vulkan # P3 vulkan slow https://github.com/mpv-player/mpv/issues/13019
border=no # uosc rec # убирает системный titlebar
osd-bar=no # uosc rec
hwdec=auto-copy # <2026-05-11 Mon> декодирование на GPU без удержания в горячем состоянии 
# cache=yes
# fbo-format=auto
# hwdec=no
# hwdec-codecs=h264,vc1,hevc,vp8,vp9,av1,prores
# cache-secs=60
# gapless-audio=yes
# autosync=30
# cache-on-disk=no
# gpu-shader-cache=yes
# audio-channels=2
# vd-lavc-dr= auto
fs=no #fullscreen
keep-open=yes
# # ontop=no
# geometry=50%:50%
# autofit=100%x100%
# autofit-larger=90%x90%
keepaspect=yes # (default - yes) # если no, то при maximize картинка тянется
keepaspect-window=no # (default - yes) # сохранять черные полосы, не резать окно. полезно при maximize 
scale=ewa_lanczos
dscale=mitchell
cscale=ewa_lanczos
#кажется с этим лучше должно быть. <2026-05-11 Mon> не оказывает влияния на p0
video-sync=display-resample
interpolation=yes
tscale=mitchell
