#!/bin/bash
exec 2>&1
export USER=snake
export HOME=/home/$USER
export PATH=$HOME/.local/bin:/home/snake/.local/state/nix/profile/bin:$PATH
export XAUTHORITY=/home/snake/.local/share/sx/xauthority
export XDG_RUNTIME_DIR=/run/user/$(id -g $USER)

cd $HOME
#exec /usr/bin/emacs --fg-daemon=vanilla
#exec $HOME/.local/state/nix/profile/bin/emacs --fg-daemon=vanilla
exec /usr/local/bin/emacs --fg-daemon=vanilla
