server:
	username: _unbound
	num-threads: 4

	auto-trust-anchor-file: "/etc/unbound/root.key"

	root-hints: "/etc/unbound/root.hints"
  # logfile: "/var/log/unbound.log"
  logfile: ""
  verbosity: 2


  #DNS-over-TLS
  tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

  chroot: ""
  #chroot: "/etc/unbound"

	interface: 127.0.0.1
  interface: 10.0.0.1     # docker0 (when active)
  interface: 10.0.1.1     # k3d-net bridge
  interface: 169.254.0.1  # unbound-if
  interface: 192.168.0.11 # enp3s0 

  port:       53   
	do-ip4:     yes   
	do-udp:     yes     
	do-tcp:     yes
	do-daemonize: yes

	#DNS Cache
	cache-min-ttl: 300 	
	cache-max-ttl: 86400

  neg-cache-size: 16m

  # prefetch: yes
  # prefetch-key: yes

	cache-max-negative-ttl: 3600 #default 3600

  rrset-cache-size: 100m
  msg-cache-size: 50m

	#Сокрытие информации
	hide-identity: yes
	hide-version: yes

	#Не запрашивать локальный хост (DNSCrypt-proxy)
	do-not-query-localhost: no

  #On Linux, set so-reuseport: yes, that will significantly improve UDP performance
  so-reuseport: yes # default yes 

	# ACL
  # access-control: 0.0.0.0/0 allow
	access-control: 127.0.0.0/8 allow
	access-control: 192.168.0.0/24 allow # local network 
  access-control: 10.0.0.0/24 allow  # docker0 сеть
  access-control: 10.0.1.0/24 allow  # K3D сеть
  access-control: 169.254.0.0/16 allow # unbound-if


	forward-zone:
		name: "."
		forward-addr: 127.0.0.1@54 # dnscrypt-proxy
