server:
	username: _unbound
	num-threads: 4

	auto-trust-anchor-file: "/etc/unbound/root.key"

	root-hints: "/etc/unbound/root.hints"
  logfile: ""
  verbosity: 1
  #log-queries: yes
  #log-replies: yes


  #DNS-over-TLS
  tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

  chroot: ""

  interface: 192.168.0.11
  interface: 127.0.0.1

  port:       53   
	do-ip4:     yes   
	do-udp:     yes     
	do-tcp:     yes
	do-daemonize: yes

	#DNS Cache
	cache-min-ttl: 300 	
	cache-max-ttl: 86400

  neg-cache-size: 16m

  prefetch: yes
  prefetch-key: yes

	cache-max-negative-ttl: 3600 # default 3600

  rrset-cache-size: 100m
  msg-cache-size: 50m

	#Сокрытие информации
	hide-identity: yes
	hide-version: yes

  #test
  serve-expired: yes                 # default no
  serve-expired-ttl: 86400           # default 1 day 
  serve-expired-ttl-reset: no        # default no 
  serve-expired-reply-ttl: 30        # default 30 
  serve-expired-client-timeout: 500  # 0.5. default 1800
  serve-original-ttl: no             # default no

	#Не запрашивать локальный хост (DNSCrypt-proxy)
	do-not-query-localhost: no

  #On Linux, set so-reuseport: yes, that will significantly improve UDP performance
  so-reuseport: yes # default yes 

	# ACL
	access-control: 127.0.0.0/8 allow
	access-control: 192.168.0.0/24 allow  # local network
  access-control: 10.0.0.0/8 allow      # 10.x.x.x 
  access-control: 172.16.0.0/12 allow   # Docker

  private-address: 192.168.0.0/16
  private-address: 172.16.0.0/12
  private-address: 10.0.0.0/8
  private-address: 169.254.0.0/16


	forward-zone:
		name: "."
		forward-addr: 127.0.0.1@54 # dnscrypt-proxy
