---
- name: Create dotfiles directories
  file:
    path: "{{ dotfiles_dir }}/{{ item }}"
    state: directory
  loop:
    - 'ansible'
    - 'ansible_main'
    - 'emacs'
    - 'emacs/dict'
    - 'emacs/lisp'
    - 'emacs/templates'
    - 'zsh'
    - 'containers'
    - 'wireplumber/wireplumber.conf.d'
    - 'libvirt'
    - 'mpv'
    - 'nvim'
    - 'ranger'

- name: Create user-specific directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ dotfiles_dir }}/.local/bin", mode: '0775' }
    - { path: "{{ dotfiles_dir }}/.gnupg", mode: '0700' }
    - { path: "{{ dotfiles_dir }}/.local/rawservices", mode: '0775' }

- name: Create system configuration directories
  become: true
  become_method: sudo
  file:
    path: "{{ dotfiles_dir }}/etc/{{ item }}"
    state: directory
  loop:
    - 'pam.d'
    - 'profile.d'
    - 'smtpd'
    - 'dnscrypt-proxy'
    - 'unbound'
    - 'sv'
    - 'sv/agetty-tty1'
    - 'sv/amneziavpn'
    - 'sv/runsvdir-snake'
    - 'sv/determinate-nixd'
    - 'sv/nix-daemon'
    - 'sv/nixgpu'
    - 'sv/smtpd_bypass'
    - 'dracut.conf.d'
    - 'logrotate.d'
    - 'iptables'
    - 'sudoers.d'
    - 'X11'
    - 'X11/xorg.conf.d'
    - 'zsh'
  tags:
    - create_dirs
