---
- name: Copy system configuration directories
  become: true
  become_method: sudo
  synchronize:
    src: "{{ system_config_dir }}/{{ item }}/"
    dest: "{{ dotfiles_dir }}/etc/{{ item }}/"
    delete: yes
  loop:
    - 'dracut.conf.d'
    - 'iptables'
    - 'sudoers.d'
    - 'X11'

- name: Ensure parent directories exist for individual files
  become: true
  become_method: sudo
  file:
    path: "{{ dotfiles_dir }}/etc/{{ item | dirname }}"
    state: directory
  loop:
    - 'pam.d/login'
    - 'profile.d/fixdbus.sh'
    - 'smtpd/smtpd.conf'
    - 'zsh/zshenv'
    - 'sv/agetty-autologin-tty1/run'
    - 'sv/amneziavpn/run'
    - 'sv/runsvdir-snake/run'

- name: Copy system configuration files
  become: true
  become_method: sudo
  copy:
    src: "{{ system_config_dir }}/{{ item }}"
    dest: "{{ dotfiles_dir }}/etc/{{ item }}"
    remote_src: yes
  loop:
    - 'dnscrypt-proxy/dnscrypt-proxy.toml'
    - 'unbound/unbound.conf'
    - 'pam.d/login'
    - 'profile.d/fixdbus.sh'
    - 'profile.d/nix.sh'
    - 'smtpd/smtpd.conf'
    - 'sv/agetty-autologin-tty1/run'
    - 'sv/amneziavpn/run'
    - 'sv/runsvdir-snake/run'
    - 'dhcpcd.conf'
    - 'zshenv'
    - 'environment'
    - 'resolv.conf'
    - 'rsyslog.conf'
    - 'sysctl.conf'
