---
- name: Copy system configuration directories
  become: true
  become_method: sudo
  synchronize:
    src: "{{ system_config_dir }}/{{ item }}/"
    dest: "{{ dotfiles_dir }}/etc/{{ item }}/"
    delete: yes
  loop:
    - 'docker'
    - 'dracut.conf.d'
    - 'sudoers.d'
    - 'xbps.d'

- name: Copy system configuration files
  become: true
  become_method: sudo
  copy:
    src: "{{ system_config_dir }}/{{ item }}"
    dest: "{{ dotfiles_dir }}/etc/{{ item }}"
    remote_src: yes
  loop:
    - 'dnscrypt-proxy/dnscrypt-proxy.toml'
    - 'unbound/unbound.conf'
    - 'iptables/iptables.rules'
    - 'pam.d/login'
    - 'smtpd/smtpd.conf'
    - 'sv/agetty-tty1/conf'
    - 'sv/amneziavpn/run'
    - 'sv/runsvdir-snake/run'
    - 'sv/nix-daemon/run'
    - 'sv/determinate-nixd/run'
    - 'sv/smtpd_bypass/run'
    - 'sv/smtpd_bypass/finish'
    - 'dhcpcd.conf'
    - 'zsh/zshenv'
    - 'nftables.conf'
    - 'logrotate.d/rsyslog'
    - 'logrotate.d/additional-logs'
    - 'X11/xorg.conf.d/30-keyboard.conf'
    - 'X11/xorg.conf.d/50-mouse-acceleration.conf'
    - 'X11/xorg.conf'
    - 'X11/Xwrapper.config'
    - 'logrotate.conf'
    - 'resolv.conf'
    - 'rsyslog.conf'
    - 'sysctl.conf'
